using System;

namespace ScrapingFromOurOwn {
	
	// languages as seen in AO3's 'Post New Work' form's language dropdown menu
	// numeric values taken from the same form
	public enum Language {
		UNDEFINED = 0,
		Afrikaans = 73,
		العربية = 34,
		беларуская = 28,
		Български_език = 29,
		বাংলা = 79,
		Bosanski = 82,
		brezhoneg = 103,
		Català = 4,
		Chinuk_Wawa = 98,
		Čeština = 5,
		Cymraeg = 43,
		Dansk = 6,
		Deutsch = 7,
		Ελληνικά = 27,
		English = 1,
		Esperanto = 45,
		Español = 9,
		eesti_keel = 51,
		فارسی = 2,
		Suomi = 23,
		Filipino = 26,
		Français = 8,
		Gaeilge = 10,
		Gàidhlig = 42,
		Sprēkō_Þiudiskō = 69,
		Galego = 93,
		עברית = 33,
		हिन्दी = 37,
		Hrvatski = 11,
		Magyar = 16,
		Interlingua = 84,
		Bahasa_Indonesia = 38,
		Íslenska = 12,
		Italiano = 13,
		日本語 = 36,
		ქართული = 106,
		한국어 = 35,
		Lingua_latina = 41,
		Langue_des_signes_québécoise = 109,
		Lëtzebuergesch = 87,
		Lietuvių_kalba = 15,
		Latviešu_valoda = 14,
		മലയാളം = 95,
		македонски = 100,
		मराठी = 46,
		Bahasa_Malaysia = 56,
		Plattdüütsch = 70,
		Nederlands = 17,
		Norsk = 18,
		ਪੰਜਾਬੀ = 3,
		Polski = 19,
		Português_brasileiro = 20,
		Português_europeu = 65,
		Khuzdul = 76,
		Quenya = 50,
		Română = 21,
		Русский = 30,
		Sindarin = 75,
		Slovenčina = 53,
		Slovenščina = 72,
		af_Soomaali = 64,
		Shqip = 22,
		српски = 31,
		Svenska = 25,
		Kiswahili = 58,
		தமிழ் = 90,
		ไทย = 47,
		tlhIngan_Hol = 49,
		Thermian = 48,
		Türkçe = 24,
		Українська = 32,
		Tiếng_Việt = 44,
		中文 = 40
	}
}